name = "idea-to-gold"
compatibility_date = "2024-08-30"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

# Pages 配置
pages_build_output_dir = ".vercel/output/static"

# 环境变量
[env.production.vars]
# 在 Cloudflare Pages 控制台中设置这些环境变量
# SUPABASE_URL = "your-supabase-url"
# SUPABASE_ANON_KEY = "your-supabase-anon-key"
# SUPABASE_SERVICE_ROLE_KEY = "your-supabase-service-role-key"

[env.preview.vars]
# 预览环境的环境变量

# Node.js 兼容性
[build.environment_variables]
NODE_VERSION = "18"